//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LANUG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public Sponsor()
        {
            this.Meetings = new HashSet<Meeting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public string LogoURL { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime Modified { get; set; }
        public int ModifiedById { get; set; }
    
        public virtual ICollection<Meeting> Meetings { get; set; }
    }
}
